name: "generator"
on:
  repository_dispatch:
    types: [generate]
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
      with:
        path: "yeoman-generator-runner"
    -
      uses: ./
      with:
        generator: webapp
        package: generator-webapp
        github-token: ${{ secrets.GITHUB_TOKEN }}
        cwd: yeoman-generator-runner/examples/webapp
        git-remote-origin-url: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        untracked-files: |
          [
            "app/*",
            "test/*",
            "package.json"
          ]
        answers: |
          {
            "ui": "bdd",
            "rjs": false,
            "features": [],
            "includeJQuery": false
          }
